type Guest {
  id: ID!
  firstName: String!
  lastName: String!
  attending: Boolean!
}

type Query {
  guests: [Guest]
}

type Mutation {
  createGuestMutation(
    firstName: String!
    lastName: String!
    attending: Boolean!
  ): Guest
  updateGuestMutation(id: ID!, attending: Boolean!): Guest
  deleteGuestMutation(id: ID!): Boolean
}
